global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: taskify-api
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:5271"]
        labels:
          service: taskify-api

  - job_name: taskify-web
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:5237"]
        labels:
          service: taskify-web
